#API
available_items:
  methods: [GET]
  path: /items/available
  controller: Bbasinski\WarehouseBundle\Controller\ItemsController::available
unavailable_items:
  methods: [GET]
  path: /items/unavailable
  controller: Bbasinski\WarehouseBundle\Controller\ItemsController::unavailable
item_by_id:
  methods: [GET]
  path: /items/{id}
  controller: Bbasinski\WarehouseBundle\Controller\ItemsController::getById
edit_item:
  methods: [POST]
  path: /items/{id}
  controller: Bbasinski\WarehouseBundle\Controller\ItemsController::edit
delete_item:
  methods: [DELETE]
  path: /items/{id}
  controller: Bbasinski\WarehouseBundle\Controller\ItemsController::delete
add_item:
  methods: [POST]
  path: /items
  controller: Bbasinski\WarehouseBundle\Controller\ItemsController::add
items_amount_over:
  methods: [GET]
  path: /items/amount/over/{amount}
  controller: Bbasinski\WarehouseBundle\Controller\ItemsController::amountOver

#CLIENT
client_endpoints:
  path: /
  controller: Bbasinski\WarehouseBundle\Controller\ClientController::endpoints
  methods: [GET]
client_add:
  path: /add
  controller: Bbasinski\WarehouseBundle\Controller\ClientController::add
  methods: [GET, POST]
client_edit:
  path: /edit/{itemId}
  controller: Bbasinski\WarehouseBundle\Controller\ClientController::edit
  methods: [GET, POST]

