services:
  Bbasinski\WarehouseBundle\DataFixtures\ItemFixtures:
    tags: ['doctrine.fixture.orm']
  Bbasinski\WarehouseBundle\Repository\ItemRepository:
    tags: ['doctrine.repository_service']
    arguments: ['@Doctrine\Common\Persistence\ManagerRegistry']
  Bbasinski\WarehouseBundle\Controller\ItemsController:
    autowire: true
    tags: ['controller.service_arguments']
  Bbasinski\WarehouseBundle\Controller\ClientController:
    autowire: true
    tags: ['controller.service_arguments']
  Bbasinski\WarehouseBundle\Command\ConfigCommand:
    tags: ['console.command']
  Bbasinski\WarehouseBundle\Command\DatabaseCommand:
    tags: ['console.command']
  Bbasinski\WarehouseBundle\Service\AddItemService:
    autowire: true
