services:
  Bbasinski\WarehouseBundle\DataFixtures\ItemFixtures:
    tags: ['doctrine.fixture.orm']
  Bbasinski\WarehouseBundle\Repository\ItemRepository:
    tags: ['doctrine.repository_service']
    arguments: ['@Doctrine\Common\Persistence\ManagerRegistry']
  Bbasinski\WarehouseBundle\Controller\:
    resource: '../../Controller'
    autowire: true
    tags: ['controller.service_arguments']
  Bbasinski\WarehouseBundle\Command\:
    resource: '../../Command'
    tags: ['console.command']
  Bbasinski\WarehouseBundle\Service\:
    resource: '../../Service'
    autowire: true
